export const customSelectStyles = {
  control: (base) => ({
    ...base,
    borderRadius: "12px",
    border: "none",
    padding: "4px 8px",
    backgroundColor: "var(--inputs)",
    fontSize: "16px",
    fontWeight: 500,
    color: "var(--main)",
    minHeight: "48px",
    boxShadow: "none",
    width: "204px",
  }),
  menu: (base) => ({
    ...base,
    width: "204px",
    marginTop: "4px",
    borderRadius: "12px",
    backgroundColor: "var(--inputs)",
    zIndex: 100,
    overflow: "hidden",
  }),
  option: (base, state) => ({
    ...base,
    fontSize: "16px",
    fontWeight: 500,
    backgroundColor: "transparent",
    color: state.isFocused ? "var(--main)" : "var(--gray)",
    cursor: "pointer",
  }),
  singleValue: (base) => ({
    ...base,
    color: "var(--main)",
  }),
  dropdownIndicator: (base) => ({
    ...base,
    color: "var(--gray)",
  }),
};
